use_frameworks!

platform :ios, '9.0'

target 'FloatingLableTextField_Example' do
  pod 'FloatingLableTextField', :path => '../'

  target 'FloatingLableTextField_Tests' do
    inherit! :search_paths

    
  end
end
