use_frameworks!

platform :ios, '9.0'

target 'FloatigLableTextField_Example' do
  pod 'FloatigLableTextField', :path => '../'

  target 'FloatigLableTextField_Tests' do
    inherit! :search_paths

    
  end
end
